In [4]:
import pandas as pd

In [3]:
df = pd.read_csv("car_ownership.csv")
df.head(5)

   monthly_salary  owns_car
0           22000         0
1           25000         0
2           47000         1
3           52000         0
4           46000         1

In [16]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

# Step 1: Features and target
X = df[['monthly_salary']]  # double brackets for DataFrame
y = df['owns_car']

# Step 2: Split the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 42)

# Step 3: Model training
model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [19]:
X_test.head()

    monthly_salary
8            62000
13           29000
9            61000
21           26000
0            22000

In [17]:
model.predict(X_test)

array([1, 0, 1, 0, 0, 0, 0, 1, 0])

In [22]:
y_test.tolist()

[1, 0, 1, 0, 0, 0, 1, 1, 0]

In [18]:
model.predict_proba(X_test)

array([[0.04530932, 0.95469068],
       [0.80955349, 0.19044651],
       [0.05158003, 0.94841997],
       [0.86480041, 0.13519959],
       [0.91687254, 0.08312746],
       [0.82967465, 0.17032535],
       [0.87995016, 0.12004984],
       [0.07564619, 0.92435381],
       [0.84806892, 0.15193108]])

In [23]:
model.score(X_test, y_test)

0.8888888888888888

In [33]:
model.coef_, model.intercept_

(array([[0.00013621]]), array([-5.39725076]))

In [37]:
import math

def sigmoid(Z):
    y = 1/ (1 + math.exp(-Z))
    return y

def prediction_func(X):
    Z = model.coef_ * X + model.intercept_
    y = sigmoid(Z)
    return y

prediction_func(62000)

/var/folders/g6/tsh89k751tn8lxp3pdk7rjjw0000gn/T/ipykernel_49828/4193985941.py:4: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  y = 1/ (1 + math.exp(-Z))

0.954690678813166

In [38]:
import math

def prediction_func(X, model):
    Z = model.coef_ * X + model.intercept_
    y = 1/ (1 + math.exp(-Z))
    return y

prediction_func(62000, model)

/var/folders/g6/tsh89k751tn8lxp3pdk7rjjw0000gn/T/ipykernel_49828/2834315717.py:5: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  y = 1/ (1 + math.exp(-Z))

0.954690678813166